/**
 * AI-Generated Likelihood Detection Module
 *
 * Analyzes websites for signals indicating AI-generated content, scam patterns,
 * and automated site construction. Combines deterministic markup/infrastructure
 * signals with Claude-based content analysis.
 *
 * Extracted from lib/extractors.ts for modularity.
 */

import { z } from "zod";
import { createHash } from "crypto";
import { fetchWithBrowser } from "./browser";
import { prisma } from "./prisma";
import type { DataPointExtractionResult } from "./extractors";

// Re-use shared infrastructure from extractors
import {
  fetchRobotsTxtCached,
  getAnthropic,
  rateLimitedClaudeCall,
  extractTextContent,
} from "./extractors";

// ── Schema ──────────────────────────────────────────────────────────────────

const aiGeneratedLikelihoodSchema = z.object({
  ai_generated_score: z.number().int().min(0).max(100),
  confidence: z.number().int().min(0).max(100),
  subscores: z.object({
    content: z.number().int().min(0).max(100),
    markup: z.number().int().min(0).max(100),
    infrastructure: z.number().int().min(0).max(100),
  }),
  signals: z.object({
    generator_meta: z.string().nullable(),
    tech_hints: z.array(z.string()),
    ai_markers: z.array(z.string()),
    suspicious_content_patterns: z.array(z.string()).optional(),
    infrastructure: z.object({
      has_robots_txt: z.boolean(),
      has_sitemap: z.boolean(),
      has_favicon: z.boolean(),
      free_hosting: z.string().nullable(),
      seo_score: z.number().int().min(0).max(100),
      is_boilerplate: z.boolean(),
    }),
  }),
  reasons: z.array(z.string()),
  notes: z.string().nullable(),
});

export type AiGeneratedLikelihood = z.infer<typeof aiGeneratedLikelihoodSchema>;

// ── Constants ───────────────────────────────────────────────────────────────

const MAX_HTML_SNIPPET_SIZE = 20 * 1024;
const MAX_TEXT_SNIPPET_SIZE = 8 * 1024;

const SITE_BUILDER_PATTERNS: Array<{
  pattern: RegExp;
  name: string;
  type: "builder" | "framework" | "cms";
  aiScore: number;
}> = [
  { pattern: /generator["']?\s*[:=]\s*["']?Framer/i, name: "Framer", type: "builder", aiScore: 75 },
  { pattern: /framer-/i, name: "Framer", type: "builder", aiScore: 70 },
  { pattern: /generator["']?\s*[:=]\s*["']?Webflow/i, name: "Webflow", type: "builder", aiScore: 65 },
  { pattern: /webflow/i, name: "Webflow", type: "builder", aiScore: 60 },
  { pattern: /generator["']?\s*[:=]\s*["']?Wix/i, name: "Wix", type: "builder", aiScore: 60 },
  { pattern: /wix\.com/i, name: "Wix", type: "builder", aiScore: 55 },
  { pattern: /generator["']?\s*[:=]\s*["']?Squarespace/i, name: "Squarespace", type: "builder", aiScore: 55 },
  { pattern: /squarespace/i, name: "Squarespace", type: "builder", aiScore: 50 },
  { pattern: /generator["']?\s*[:=]\s*["']?Carrd/i, name: "Carrd", type: "builder", aiScore: 70 },
  { pattern: /carrd\.co/i, name: "Carrd", type: "builder", aiScore: 65 },
  { pattern: /generator["']?\s*[:=]\s*["']?Notion/i, name: "Notion", type: "builder", aiScore: 60 },
  { pattern: /super\.so|notion\.site/i, name: "Notion Site", type: "builder", aiScore: 60 },
  { pattern: /__next/i, name: "Next.js", type: "framework", aiScore: 25 },
  { pattern: /_next\//i, name: "Next.js", type: "framework", aiScore: 25 },
  { pattern: /generator["']?\s*[:=]\s*["']?Next\.js/i, name: "Next.js", type: "framework", aiScore: 30 },
  { pattern: /gatsby/i, name: "Gatsby", type: "framework", aiScore: 30 },
  { pattern: /nuxt/i, name: "Nuxt", type: "framework", aiScore: 30 },
  { pattern: /react/i, name: "React", type: "framework", aiScore: 20 },
  { pattern: /vue/i, name: "Vue", type: "framework", aiScore: 20 },
  { pattern: /svelte/i, name: "Svelte", type: "framework", aiScore: 25 },
  { pattern: /astro/i, name: "Astro", type: "framework", aiScore: 30 },
  { pattern: /generator["']?\s*[:=]\s*["']?WordPress/i, name: "WordPress", type: "cms", aiScore: 20 },
  { pattern: /wp-content/i, name: "WordPress", type: "cms", aiScore: 15 },
  { pattern: /generator["']?\s*[:=]\s*["']?Drupal/i, name: "Drupal", type: "cms", aiScore: 15 },
  { pattern: /generator["']?\s*[:=]\s*["']?Joomla/i, name: "Joomla", type: "cms", aiScore: 15 },
  { pattern: /shopify/i, name: "Shopify", type: "cms", aiScore: 35 },
];

const AI_MARKER_PATTERNS: Array<{ pattern: RegExp; description: string; score: number }> = [
  { pattern: /generated\s*by\s*ai/i, description: "Contains 'generated by AI' text", score: 40 },
  { pattern: /ai-generated/i, description: "Contains 'AI-generated' marker", score: 40 },
  { pattern: /created\s*with\s*ai/i, description: "Contains 'created with AI' text", score: 35 },
  { pattern: /<!--\s*AI\s*generated/i, description: "AI generated HTML comment", score: 30 },
  { pattern: /chatgpt|gpt-4|claude|anthropic/i, description: "References AI model names", score: 25 },
  { pattern: /lorem\s*ipsum/i, description: "Contains placeholder text", score: 15 },
];

const SUSPICIOUS_CONTENT_PATTERNS: Array<{
  pattern: RegExp;
  description: string;
  score: number;
  minMatches?: number;
}> = [
  { pattern: /(?:hahaha|hehe|hihi|lol|wow)[·\-\s]+[a-z]/i, description: "Nonsensical product name prefix (e.g., 'Hahaha·')", score: 35 },
  { pattern: /[A-Za-z]+[·•]+[A-Za-z]+\s+(?:version|edition|style|type|model)/i, description: "Unusual punctuation in product names", score: 25 },
  { pattern: /curved\s+blade\s+guard|straight\s+tube\s+pants|wide\s+leg\s+version/i, description: "Awkward literal translation patterns", score: 30 },
  { pattern: /(?:small|big|large)\s+(?:fragrance|smell)\s+(?:version|type)/i, description: "Nonsensical fragrance descriptions", score: 30 },
  { pattern: /\b(?:high\s+quality|best\s+quality|top\s+quality)\s+(?:cheap|low\s+price|discount)/i, description: "Suspicious quality + price claims", score: 25 },
  { pattern: /\b(?:factory|warehouse)\s+direct\s+(?:sale|price|shipping)/i, description: "Factory direct sale claims", score: 20 },
  { pattern: /\b(?:limited\s+time|flash\s+sale|clearance)\s+(?:\d+%\s+off|\$\d+)/i, description: "Aggressive discount language", score: 15 },
  { pattern: /\bvery\s+(?:much\s+)?(?:good|nice|beautiful)\s+(?:quality|product|item)\b/i, description: "Broken English quality claims", score: 20 },
  { pattern: /\b(?:welcome\s+to\s+)?(?:our\s+)?(?:shop|store)\s+(?:buy|purchase)\b/i, description: "Awkward shopping invitation", score: 15 },
  { pattern: /\bship(?:ping)?\s+(?:from|to)\s+(?:fast|quick|speed)/i, description: "Broken shipping description", score: 20 },
  { pattern: /\b(?:asian|china|chinese)\s+size\b/i, description: "Suspicious sizing disclaimer", score: 15 },
  { pattern: /\bplease\s+(?:check|see|read)\s+(?:size\s+)?chart\s+(?:carefully|before)/i, description: "Excessive sizing warnings", score: 10, minMatches: 3 },
  { pattern: /\b(?:only|just)\s+\d+\s+(?:left|remaining|pieces?|items?)\s+(?:in\s+stock)?/i, description: "Fake scarcity claims", score: 20 },
  { pattern: /\b(?:order|buy)\s+(?:now|today)\s+(?:get|receive)\s+(?:free|gift)/i, description: "Fake urgency with gift claims", score: 20 },
  { pattern: /\b(?:men|women|unisex)\s+(?:casual|fashion)\s+(?:streetwear|vintage)\s+(?:loose|slim)\b/i, description: "Keyword-stuffed product categories", score: 25 },
  { pattern: /\bthe\s+(?:is|are|was|were)\s+(?:very|so|too)\b/i, description: "Grammar error (article misuse)", score: 15, minMatches: 2 },
  { pattern: /\b(?:it|this|that)\s+(?:is|are)\s+(?:a|an)\s+(?:very|so)\b/i, description: "Awkward intensifier usage", score: 15, minMatches: 2 },
  { pattern: /\b(?:5\s+stars?|excellent|perfect)\s+(?:product|item|quality)\s+(?:fast|quick)\s+(?:shipping|delivery)/i, description: "Templated fake review pattern", score: 25 },
  { pattern: /\bgood\s+(?:seller|shop|store)\s+(?:recommend|recommended)\b/i, description: "Generic fake review", score: 20 },
  { pattern: /\b(?:suitable|perfect)\s+for\s+(?:daily|everyday)\s+(?:wear|use|wearing)\s+(?:and|or)\s+(?:party|dating|travel)/i, description: "Overly broad usage claims", score: 15 },
];

const FREE_HOSTING_PATTERNS: Array<{ pattern: RegExp; name: string; score: number }> = [
  { pattern: /\.onrender\.com$/i, name: "Render", score: 40 },
  { pattern: /\.vercel\.app$/i, name: "Vercel", score: 30 },
  { pattern: /\.netlify\.app$/i, name: "Netlify", score: 30 },
  { pattern: /\.github\.io$/i, name: "GitHub Pages", score: 25 },
  { pattern: /\.pages\.dev$/i, name: "Cloudflare Pages", score: 25 },
  { pattern: /\.herokuapp\.com$/i, name: "Heroku", score: 35 },
  { pattern: /\.railway\.app$/i, name: "Railway", score: 35 },
  { pattern: /\.fly\.dev$/i, name: "Fly.io", score: 30 },
  { pattern: /\.surge\.sh$/i, name: "Surge", score: 35 },
  { pattern: /\.glitch\.me$/i, name: "Glitch", score: 40 },
  { pattern: /\.replit\.app$/i, name: "Replit", score: 45 },
  { pattern: /\.web\.app$/i, name: "Firebase", score: 25 },
  { pattern: /\.firebaseapp\.com$/i, name: "Firebase", score: 25 },
];

const BOILERPLATE_PATTERNS: Array<{ pattern: RegExp; description: string }> = [
  { pattern: /<title[^>]*>(?:My App|Vite App|React App|Next\.js App|Untitled|Home|Welcome)<\/title>/i, description: "Generic title" },
  { pattern: /class="[^"]*(?:hero-content|hero-inner|hero-section)[^"]*"/i, description: "Generic hero section classes" },
  { pattern: /<meta[^>]*description[^>]*content=["'](?:Your personal app|Welcome to|A website|My website|Description here)["']/i, description: "Placeholder meta description" },
  { pattern: /<!--\s*(?:Add your content|Replace with|TODO|FIXME)\s*-->/i, description: "Template comments" },
  { pattern: /Lorem ipsum|dolor sit amet|consectetur adipiscing/i, description: "Lorem ipsum placeholder" },
];

// ── Helper Functions ────────────────────────────────────────────────────────

function detectSuspiciousContent(text: string): { patterns: string[]; score: number; reasons: string[] } {
  const detectedPatterns: string[] = [];
  const reasons: string[] = [];
  let totalScore = 0;

  for (const { pattern, description, score, minMatches = 1 } of SUSPICIOUS_CONTENT_PATTERNS) {
    const matches = text.match(new RegExp(pattern, 'gi'));
    if (matches && matches.length >= minMatches) {
      detectedPatterns.push(description);
      totalScore += score;
      reasons.push(matches.length >= 3 ? `${description} (found ${matches.length} instances)` : description);
    }
  }

  return { patterns: detectedPatterns, score: Math.min(60, totalScore), reasons: reasons.slice(0, 4) };
}

async function checkRobotsTxt(baseUrl: string): Promise<boolean> {
  const cached = await fetchRobotsTxtCached(baseUrl);
  return cached.exists;
}

async function checkSitemap(baseUrl: string): Promise<boolean> {
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    const response = await fetch(`${baseUrl}/sitemap.xml`, {
      method: "GET",
      signal: controller.signal,
      headers: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" },
    });
    clearTimeout(timeoutId);
    if (response.ok) {
      const content = await response.text();
      return /<urlset|<sitemapindex|<url>|<loc>/i.test(content);
    }
    return false;
  } catch {
    return false;
  }
}

async function checkFavicon(baseUrl: string, headHtml: string): Promise<boolean> {
  if (/<link[^>]*rel=["'](?:icon|shortcut icon|apple-touch-icon)["'][^>]*>/i.test(headHtml)) return true;
  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 5000);
    const response = await fetch(`${baseUrl}/favicon.ico`, {
      method: "HEAD",
      signal: controller.signal,
      headers: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" },
    });
    clearTimeout(timeoutId);
    return response.ok;
  } catch {
    return false;
  }
}

function calculateSeoScore(headHtml: string, fullHtml: string): number {
  let score = 0;
  if (/<title[^>]*>.{10,}<\/title>/i.test(headHtml)) {
    const titleMatch = headHtml.match(/<title[^>]*>([^<]+)<\/title>/i);
    score += (titleMatch && !/^(?:Home|Welcome|Untitled|My App|Vite App|React App)$/i.test(titleMatch[1].trim())) ? 20 : 5;
  }
  if (/<meta[^>]*name=["']description["'][^>]*content=["'][^"']{50,}["']/i.test(headHtml)) score += 20;
  else if (/<meta[^>]*name=["']description["']/i.test(headHtml)) score += 5;
  if (/<meta[^>]*property=["']og:/i.test(headHtml)) score += 15;
  if (/<meta[^>]*name=["']twitter:/i.test(headHtml)) score += 10;
  if (/<link[^>]*rel=["']canonical["']/i.test(headHtml)) score += 10;
  if (/<script[^>]*type=["']application\/ld\+json["']/i.test(fullHtml)) score += 15;
  if (/<(?:header|main|footer|article|section|nav)[^>]*>/i.test(fullHtml)) score += 10;
  return Math.min(100, score);
}

function detectFreeHosting(url: string): { name: string; score: number } | null {
  try {
    const hostname = new URL(url).hostname;
    for (const { pattern, name, score } of FREE_HOSTING_PATTERNS) {
      if (pattern.test(hostname)) return { name, score };
    }
  } catch { /* invalid URL */ }
  return null;
}

function checkBoilerplate(headHtml: string, fullHtml: string): { isBoilerplate: boolean; indicators: string[] } {
  const indicators: string[] = [];
  for (const { pattern, description } of BOILERPLATE_PATTERNS) {
    if (pattern.test(headHtml) || pattern.test(fullHtml.substring(0, 10000))) indicators.push(description);
  }
  return { isBoilerplate: indicators.length >= 2, indicators };
}

// ── Infrastructure Signals ──────────────────────────────────────────────────

async function computeInfrastructureSignals(url: string, headHtml: string, fullHtml: string) {
  const reasons: string[] = [];
  let infrastructureSubscore = 0;
  const urlObj = new URL(url);
  const baseUrl = `${urlObj.protocol}//${urlObj.host}`;

  const [hasRobotsTxt, hasSitemap, hasFavicon] = await Promise.all([
    checkRobotsTxt(baseUrl),
    checkSitemap(baseUrl),
    checkFavicon(baseUrl, headHtml),
  ]);

  const freeHosting = detectFreeHosting(url);
  const seoScore = calculateSeoScore(headHtml, fullHtml);
  const boilerplateCheck = checkBoilerplate(headHtml, fullHtml);

  if (!hasRobotsTxt) { infrastructureSubscore += 20; reasons.push("Missing robots.txt"); }
  if (!hasSitemap) { infrastructureSubscore += 15; reasons.push("Missing sitemap.xml"); }
  if (!hasFavicon) { infrastructureSubscore += 10; reasons.push("Missing favicon"); }
  if (freeHosting) { infrastructureSubscore += freeHosting.score; reasons.push(`Hosted on ${freeHosting.name} (free tier)`); }

  const seoContribution = Math.round((100 - seoScore) * 0.25);
  infrastructureSubscore += seoContribution;
  if (seoScore < 30) reasons.push("Minimal SEO setup");
  if (boilerplateCheck.isBoilerplate) { infrastructureSubscore += 20; reasons.push("Generic boilerplate structure detected"); }

  return {
    infrastructureSubscore: Math.min(100, infrastructureSubscore),
    signals: { has_robots_txt: hasRobotsTxt, has_sitemap: hasSitemap, has_favicon: hasFavicon, free_hosting: freeHosting?.name || null, seo_score: seoScore, is_boilerplate: boilerplateCheck.isBoilerplate },
    reasons: reasons.slice(0, 4),
  };
}

// ── Markup Signals ──────────────────────────────────────────────────────────

function extractHeadHtml(html: string): string {
  const headMatch = html.match(/<head[^>]*>([\s\S]*?)<\/head>/i);
  return headMatch ? headMatch[0] : html.substring(0, 5000);
}

function generateSha256(content: string): string {
  return createHash("sha256").update(content).digest("hex");
}

function extractRelevantHeaders(headers?: Record<string, string>): Record<string, string | null> {
  const relevant: Record<string, string | null> = { server: null, "x-powered-by": null, "x-generator": null };
  if (!headers) return relevant;
  for (const [key, value] of Object.entries(headers)) {
    const lowerKey = key.toLowerCase();
    if (lowerKey in relevant) relevant[lowerKey] = value;
  }
  return relevant;
}

function computeMarkupSignals(headHtml: string, fullHtml: string, headers?: Record<string, string>, textContent?: string) {
  const techHints: string[] = [];
  const aiMarkers: string[] = [];
  const reasons: string[] = [];
  let generatorMeta: string | null = null;
  let markupSubscore = 0;

  const detectedBuilders = new Map<string, number>();
  for (const { pattern, name, aiScore } of SITE_BUILDER_PATTERNS) {
    if (pattern.test(headHtml) || pattern.test(fullHtml.substring(0, 50000))) {
      if (!detectedBuilders.has(name) || detectedBuilders.get(name)! < aiScore) detectedBuilders.set(name, aiScore);
    }
  }

  for (const [name, score] of detectedBuilders) {
    techHints.push(name.toLowerCase().replace(/\s+/g, "-"));
    if (!generatorMeta) generatorMeta = name;
    if (score > markupSubscore) markupSubscore = score;
  }

  if (generatorMeta) {
    const builderType = SITE_BUILDER_PATTERNS.find((p) => p.name === generatorMeta)?.type;
    if (builderType === "builder") reasons.push(`Built with ${generatorMeta} (no-code builder)`);
    else if (builderType === "framework") reasons.push(`Uses ${generatorMeta} framework`);
    else reasons.push(`Powered by ${generatorMeta}`);
  }

  for (const { pattern, description, score } of AI_MARKER_PATTERNS) {
    if (pattern.test(fullHtml)) {
      aiMarkers.push(description);
      markupSubscore = Math.min(100, markupSubscore + score);
      reasons.push(description);
    }
  }

  const contentToAnalyze = textContent || fullHtml;
  const suspiciousContent = detectSuspiciousContent(contentToAnalyze);
  const suspiciousContentPatterns = suspiciousContent.patterns;
  if (suspiciousContent.score > 0) {
    markupSubscore = Math.min(100, markupSubscore + suspiciousContent.score);
    reasons.push(...suspiciousContent.reasons.slice(0, 2));
  }

  if (headers) {
    const relevantHeaders = extractRelevantHeaders(headers);
    if (relevantHeaders.server?.toLowerCase().includes("vercel")) techHints.push("vercel");
    if (relevantHeaders.server?.toLowerCase().includes("netlify")) techHints.push("netlify");
    if (relevantHeaders["x-powered-by"]?.toLowerCase().includes("next.js") && !techHints.includes("next.js")) techHints.push("next.js");
  }

  if (/tailwind|tw-/i.test(fullHtml)) techHints.push("tailwind");

  return {
    markupSubscore: Math.min(100, Math.max(0, markupSubscore)),
    generatorMeta,
    techHints: [...new Set(techHints)],
    aiMarkers,
    suspiciousContentPatterns,
    reasons: reasons.slice(0, 5),
  };
}

// ── Artifact Storage ────────────────────────────────────────────────────────

async function storeHomepageArtifacts(scanId: string, url: string, html: string, text: string, contentType?: string): Promise<void> {
  const htmlSha256 = generateSha256(html);
  const textSha256 = generateSha256(text);
  const htmlSnippet = html.substring(0, MAX_HTML_SNIPPET_SIZE);
  const textSnippet = text.substring(0, MAX_TEXT_SNIPPET_SIZE);

  await prisma.$transaction([
    prisma.scanArtifact.upsert({
      where: { scanId_type: { scanId, type: "homepage_html" } },
      create: { scanId, url, type: "homepage_html", sha256: htmlSha256, snippet: htmlSnippet, contentType: contentType || "text/html" },
      update: { url, sha256: htmlSha256, snippet: htmlSnippet, contentType: contentType || "text/html", fetchedAt: new Date() },
    }),
    prisma.scanArtifact.upsert({
      where: { scanId_type: { scanId, type: "homepage_text" } },
      create: { scanId, url, type: "homepage_text", sha256: textSha256, snippet: textSnippet, contentType: "text/plain" },
      update: { url, sha256: textSha256, snippet: textSnippet, contentType: "text/plain", fetchedAt: new Date() },
    }),
  ]);
}

async function getOrFetchHomepageArtifacts(scanId: string, url: string): Promise<{
  htmlSnippet: string;
  textSnippet: string;
  headHtml: string;
  headers?: Record<string, string>;
} | null> {
  const existingArtifacts = await prisma.scanArtifact.findMany({ where: { scanId } });
  const htmlArtifact = existingArtifacts.find((a) => a.type === "homepage_html");
  const textArtifact = existingArtifacts.find((a) => a.type === "homepage_text");

  if (htmlArtifact && textArtifact) {
    return { htmlSnippet: htmlArtifact.snippet, textSnippet: textArtifact.snippet, headHtml: extractHeadHtml(htmlArtifact.snippet) };
  }

  try {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 15000);
    const response = await fetch(url, {
      signal: controller.signal,
      headers: { "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36" },
    });
    clearTimeout(timeoutId);

    if (!response.ok) {
      console.warn(`Failed to fetch homepage for AI analysis: ${response.status}`);
      return null;
    }

    const html = await response.text();
    const contentType = response.headers.get("content-type") || undefined;
    const headers: Record<string, string> = {};
    response.headers.forEach((value, key) => { headers[key] = value; });
    const text = extractTextContent(html);
    await storeHomepageArtifacts(scanId, url, html, text, contentType);

    return {
      htmlSnippet: html.substring(0, MAX_HTML_SNIPPET_SIZE),
      textSnippet: text.substring(0, MAX_TEXT_SNIPPET_SIZE),
      headHtml: extractHeadHtml(html),
      headers,
    };
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    const isSSLError = errorMessage.includes('SSL') || errorMessage.includes('TLS') ||
      errorMessage.includes('certificate') || (error as NodeJS.ErrnoException)?.code?.includes('SSL');

    if (isSSLError) {
      console.warn(`SSL error fetching homepage, falling back to browser: ${errorMessage}`);
      try {
        const browserResult = await fetchWithBrowser(scanId, url, 'ai_analysis_fallback', {
          waitForNetworkIdle: false, additionalWaitMs: 2000, expandSections: false,
        });
        if (browserResult.content) {
          const html = browserResult.content;
          const text = extractTextContent(html);
          const contentType = browserResult.contentType || undefined;
          await storeHomepageArtifacts(scanId, url, html, text, contentType);
          return {
            htmlSnippet: html.substring(0, MAX_HTML_SNIPPET_SIZE),
            textSnippet: text.substring(0, MAX_TEXT_SNIPPET_SIZE),
            headHtml: extractHeadHtml(html),
          };
        }
      } catch (browserError) {
        console.error("Browser fallback also failed:", browserError);
      }
    }

    console.error("Error fetching homepage for AI analysis:", error);
    return null;
  }
}

// ── Claude Analysis ─────────────────────────────────────────────────────────

async function analyzeWithClaude(
  textSnippet: string,
  headHtml: string,
  headers: Record<string, string | null>,
  deterministicSignals: ReturnType<typeof computeMarkupSignals>,
  infrastructureSignals: Awaited<ReturnType<typeof computeInfrastructureSignals>>
): Promise<AiGeneratedLikelihood> {
  const currentYear = new Date().getFullYear();
  const currentDate = new Date().toISOString().split('T')[0];

  const systemPrompt = `You are an AI content analyst helping assess whether a website's homepage appears to be AI-generated or is a potential scam/fake store.

IMPORTANT: Today's date is ${currentDate}. The current year is ${currentYear}. When evaluating copyright notices or dates, consider ${currentYear} to be the current year, NOT a future date.

IMPORTANT GUIDELINES:
- You are providing a HEURISTIC ESTIMATE, not a definitive judgment
- Be CONSERVATIVE: if evidence is unclear, lean toward moderate scores (40-60) with lower confidence
- Use "likelihood" and "estimate" language, never claim certainty
- Consider that many legitimate websites use templates, no-code builders, or AI assistance
- Low text volume or minimal content should reduce confidence, not increase AI score

SUSPICIOUS CONTENT INDICATORS (strong signals of AI-generated scam sites):
- Nonsensical or gibberish product names (e.g., "Hahaha·Round Neck Version", "Curved Blade Guard Trousers")
- Unusual punctuation in product names (middle dots ·, random symbols)
- Broken English or awkward machine translation artifacts
- Overly literal translations that don't make sense in context
- Keyword-stuffed category combinations ("Men Casual Fashion Streetwear Vintage Loose")
- Fake urgency/scarcity claims ("Only 3 left!", "Flash sale ends in...")
- Templated fake reviews ("5 stars, fast shipping, good seller recommend")
- Suspicious sizing disclaimers ("Asian size", "Please check size chart carefully before order")
- Factory direct/warehouse sale claims combined with very low prices

SCORING CRITERIA for content_subscore (0-100):
- 0-30: Content appears naturally written, unique voice, specific details, industry expertise
- 31-50: Mixed signals or insufficient content to assess
- 51-70: Some generic patterns, template-like phrasing, but could be human-written
- 71-85: Strong AI markers (overly formal, generic buzzwords, lacks specificity)
- 86-100: Clear scam indicators (nonsensical names, broken English, fake reviews)

SCORING CRITERIA for markup_subscore (0-100):
- 0-30: Custom development, unique structure, hand-crafted feel
- 31-50: Standard framework usage, common patterns
- 51-70: No-code builder or template-based, but well-customized
- 71-100: Heavy AI/template markers, minimal customization

SCORING CRITERIA for infrastructure_subscore (0-100):
- 0-30: Professional setup with robots.txt, sitemap, good SEO, custom domain
- 31-50: Basic setup, some missing elements
- 51-70: Minimal setup, free hosting, missing key files
- 71-100: Very sparse setup, free hosting, no SEO, boilerplate

Return ONLY valid JSON matching this exact schema:
{
  "ai_generated_score": <0-100 integer>,
  "confidence": <0-100 integer>,
  "subscores": { "content": <0-100>, "markup": <0-100>, "infrastructure": <0-100> },
  "signals": {
    "generator_meta": <string or null>,
    "tech_hints": [<string array>],
    "ai_markers": [<string array>],
    "suspicious_content_patterns": [<string array>],
    "infrastructure": { "has_robots_txt": <bool>, "has_sitemap": <bool>, "has_favicon": <bool>, "free_hosting": <string or null>, "seo_score": <0-100>, "is_boilerplate": <bool> }
  },
  "reasons": [<3-6 concise bullet strings>],
  "notes": <string or null>
}`;

  const userPrompt = `Analyze this homepage for AI-generated likelihood and potential scam indicators.

DETECTED SIGNALS (from deterministic analysis):
- Generator: ${deterministicSignals.generatorMeta || "Unknown"}
- Tech hints: ${deterministicSignals.techHints.join(", ") || "None detected"}
- AI markers found: ${deterministicSignals.aiMarkers.join(", ") || "None"}
- Suspicious content patterns found: ${deterministicSignals.suspiciousContentPatterns.join(", ") || "None"}
- Initial markup subscore: ${deterministicSignals.markupSubscore}

INFRASTRUCTURE SIGNALS:
- Has robots.txt: ${infrastructureSignals.signals.has_robots_txt}
- Has sitemap: ${infrastructureSignals.signals.has_sitemap}
- Has favicon: ${infrastructureSignals.signals.has_favicon}
- Free hosting: ${infrastructureSignals.signals.free_hosting || "No (custom domain)"}
- SEO score: ${infrastructureSignals.signals.seo_score}/100
- Boilerplate detected: ${infrastructureSignals.signals.is_boilerplate}
- Initial infrastructure subscore: ${infrastructureSignals.infrastructureSubscore}

RESPONSE HEADERS:
${JSON.stringify(headers, null, 2)}

<HEAD> SECTION (truncated):
${headHtml.substring(0, 3000)}

VISIBLE TEXT CONTENT (truncated):
${textSnippet}

Based on the above, provide your AI-generated likelihood assessment. Remember:
- Be conservative with extreme scores
- Reduce confidence if text is sparse or signals are mixed
- Consider that no-code builders != AI-generated content
- Missing robots.txt, sitemap, or favicon is a signal but not definitive
- Free hosting platforms increase suspicion but many legitimate projects use them
- IMPORTANT: Look carefully for nonsensical product names, broken English, and scam patterns in the text content
- If you find gibberish names like "Hahaha·Round Neck Version" or broken translations, this strongly indicates AI-generated scam content
- Include specific examples of suspicious content in the suspicious_content_patterns array
- The final ai_generated_score should be: round(0.55 * content + 0.25 * markup + 0.20 * infrastructure)`;

  try {
    const response = await rateLimitedClaudeCall(() =>
      getAnthropic().messages.create({
        model: "claude-sonnet-4-20250514",
        max_tokens: 4096,
        system: systemPrompt,
        messages: [
          { role: "user", content: userPrompt },
          { role: "assistant", content: "{" },
        ],
      })
    );

    const textBlock = response.content.find((block) => block.type === "text");
    if (!textBlock || textBlock.type !== "text") throw new Error("No response from Claude");

    let content = "{" + textBlock.text.trim();
    content = content.replace(/^```json\s*/i, "").replace(/\s*```$/, "");
    return aiGeneratedLikelihoodSchema.parse(JSON.parse(content));
  } catch (error) {
    console.error("Claude analysis error:", error);
    throw error;
  }
}

function createFallbackResult(errorMessage: string): AiGeneratedLikelihood {
  return {
    ai_generated_score: 50,
    confidence: 0,
    subscores: { content: 50, markup: 50, infrastructure: 50 },
    signals: {
      generator_meta: null,
      tech_hints: [],
      ai_markers: [],
      suspicious_content_patterns: [],
      infrastructure: { has_robots_txt: false, has_sitemap: false, has_favicon: false, free_hosting: null, seo_score: 0, is_boilerplate: false },
    },
    reasons: ["Analysis unavailable"],
    notes: errorMessage,
  };
}

// ── Main Entry Point ────────────────────────────────────────────────────────

export async function extractAiGeneratedLikelihood(
  scanId: string,
  url: string,
  domain: string,
  existingCrawledPages?: Map<string, string>
): Promise<DataPointExtractionResult> {
  const key = "ai_generated_likelihood";
  const label = "AI-generated likelihood";

  try {
    let htmlSnippet: string;
    let textSnippet: string;
    let headHtml: string;
    let headers: Record<string, string> | undefined;

    if (existingCrawledPages && existingCrawledPages.has(url)) {
      const html = existingCrawledPages.get(url)!;
      htmlSnippet = html.substring(0, MAX_HTML_SNIPPET_SIZE);
      textSnippet = extractTextContent(html).substring(0, MAX_TEXT_SNIPPET_SIZE);
      headHtml = extractHeadHtml(html);
      await storeHomepageArtifacts(scanId, url, html, textSnippet);
    } else {
      const artifacts = await getOrFetchHomepageArtifacts(scanId, url);
      if (!artifacts) {
        return { key, label, value: createFallbackResult("Could not fetch homepage content"), sources: [url], rawOpenAIResponse: null };
      }
      htmlSnippet = artifacts.htmlSnippet;
      textSnippet = artifacts.textSnippet;
      headHtml = artifacts.headHtml;
      headers = artifacts.headers;
    }

    const deterministicSignals = computeMarkupSignals(headHtml, htmlSnippet, headers, textSnippet);
    console.log("Computing infrastructure signals...");
    const infraSignals = await computeInfrastructureSignals(url, headHtml, htmlSnippet);
    console.log("Infrastructure signals:", infraSignals);

    const textLength = textSnippet.replace(/\s+/g, " ").trim().length;
    let confidenceAdjustment = 0;
    const additionalNotes: string[] = [];
    if (textLength < 500) { confidenceAdjustment -= 30; additionalNotes.push("Low text volume on homepage"); }
    else if (textLength < 1000) { confidenceAdjustment -= 15; additionalNotes.push("Limited text content"); }

    let result: AiGeneratedLikelihood;
    let rawResponse: any = null;

    try {
      const headersSafe = extractRelevantHeaders(headers);
      result = await analyzeWithClaude(textSnippet, headHtml, headersSafe, deterministicSignals, infraSignals);
      result.confidence = Math.max(0, Math.min(100, result.confidence + confidenceAdjustment));
      if (additionalNotes.length > 0) {
        result.notes = [result.notes, ...additionalNotes].filter(Boolean).join("; ") || null;
      }
      rawResponse = { model: "claude-sonnet-4-20250514", analysis: "completed" };
    } catch (claudeError) {
      console.error("Claude call failed, using deterministic signals only:", claudeError);
      const markupScore = deterministicSignals.markupSubscore;
      const infraScore = infraSignals.infrastructureSubscore;
      const aiScore = Math.round(0.55 * 50 + 0.25 * markupScore + 0.20 * infraScore);
      const allReasons = [...deterministicSignals.reasons, ...infraSignals.reasons].slice(0, 6);

      result = {
        ai_generated_score: aiScore,
        confidence: Math.max(0, 20 + confidenceAdjustment),
        subscores: { content: 50, markup: markupScore, infrastructure: infraScore },
        signals: {
          generator_meta: deterministicSignals.generatorMeta,
          tech_hints: deterministicSignals.techHints,
          ai_markers: deterministicSignals.aiMarkers,
          suspicious_content_patterns: deterministicSignals.suspiciousContentPatterns,
          infrastructure: infraSignals.signals,
        },
        reasons: allReasons.length > 0 ? allReasons : ["Insufficient data for content analysis"],
        notes: ["Claude unavailable - using markup and infrastructure signals only", ...additionalNotes].join("; "),
      };
      rawResponse = { error: claudeError instanceof Error ? claudeError.message : "Unknown error", fallback: true };
    }

    return { key, label, value: result, sources: [url], rawOpenAIResponse: rawResponse };
  } catch (error) {
    console.error("Error extracting AI-generated likelihood:", error);
    return {
      key, label,
      value: createFallbackResult(error instanceof Error ? error.message : "Unknown extraction error"),
      sources: [url],
      rawOpenAIResponse: { error: error instanceof Error ? error.message : "Unknown error" },
    };
  }
}
